name: well_talk
description: Well Talk | A new way to communicate your health.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_link_previewer: ^3.2.2
  http: ^1.1.0
  image_picker: ^1.0.2
  open_filex: ^4.3.2
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
